@extends('layouts.master', ['title' => 'Accrual Revenue', 'main' => 'Dashboard'])

@section('content')
<div class="app-main pt-6 flex-column flex-row-fluid" id="kt_app_main">
    <!--begin::Content wrapper-->
    <div class="d-flex flex-column flex-column-fluid">
        <!--begin::Content-->
        <div id="kt_app_content" class="app-content flex-column-fluid">
            <!--begin::Content container-->
            <div id="kt_app_content_container" class="app-container container-xxl">
                <!--begin::Card-->
                <div class="card card-flush">
                    <!--begin::Card header-->
                    <!--end::Card header-->
                    <!--begin::Card body-->
                    <div class="card-body pt-6">
                        <!--begin::Nav tabs-->
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Accrual Revenue</a>
                            </li>
                            <li class="nav-item" role="presentation">
                                <a class="nav-link" id="export-list-tab" data-bs-toggle="tab" href="#export-list" role="tab" aria-controls="export-list" aria-selected="false">Accrual Export List</a>
                            </li>
                        </ul>
                        <!--end::Nav tabs-->
                        
                        <!--begin::Tab content-->
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <div class="mb-6 d-flex flex-wrap align-items-center justify-content-between gap-4 border-0 pt-6">
                                    <h3 class="card-title align-items-start flex-column">
                                        <span class="card-label fw-bold fs-3 mb-1">Accrual Revenue</span>
                                    </h3>
                                    <div class="d-flex flex-wrap gap-4 align-items-center">
                                        <div>
                                            <div class="d-flex align-items-center">
                                                <select id="monthSelect" class="form-select form-select-sm me-2">
                                                    <option value="0">January</option>
                                                    <option value="1">February</option>
                                                    <option value="2">March</option>
                                                    <option value="3">April</option>
                                                    <option value="4">May</option>
                                                    <option value="5">June</option>
                                                    <option value="6">July</option>
                                                    <option value="7">August</option>
                                                    <option value="8">September</option>
                                                    <option value="9">October</option>
                                                    <option value="10">November</option>
                                                    <option value="11">December</option>
                                                </select>
                                                <select id="yearSelect" class="form-select form-select-sm">
                                                    <!-- Years dynamically generated by JavaScript -->
                                                </select>
                                                <input type="text" id="start_date" hidden>
                                                <input type="text" id="end_date" hidden>
                                            </div>
                                        </div>
                                        <div class="">
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-success btn-sm text-nowrap" data-bs-toggle="modal" data-bs-target="#exportExcelModal">
                                                <i class="ki-duotone ki-exit-up fs-3">
                                                    <span class="path1"></span>
                                                    <span class="path2"></span>
                                                    <span class="path3"></span>
                                                </i>
                                                Export Excel
                                            </button>

                                            <!-- Modal -->
                                            <div class="modal fade" id="exportExcelModal" tabindex="-1" aria-labelledby="exportExcelModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exportExcelModalLabel">Export Excel</h5>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <form action="{{ route('accrual-revenue.export-excel') }}" method="GET" enctype="multipart/form-data">
                                                            @method('GET')
                                                            <div class="modal-body">
                                                                <div class="mb-3">
                                                                    <label for="startMonth" class="form-label">Bulan Mulai</label>
                                                                    <input type="month" class="form-control" id="startMonth" name="start_month" required>
                                                                </div>
                                                                <div class="mb-3">
                                                                    <label for="endMonth" class="form-label">Bulan Akhir</label>
                                                                    <input type="month" class="form-control" id="endMonth" name="end_month" required
                                                                        onchange="validateMonthRange()">
                                                                </div>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                                                                <button type="submit" class="btn btn-primary">Export</button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="mb-6">
                                    <h4 class="mb-3">Chart Cash & Accural Revenue</h4>
                                    <div id="chartContainer" width="700" height="250" style="position: relative;">
                                        <div id="loadingSpinner" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); display: none;">
                                            <div class="spinner-border text-primary" role="status">
                                                <span class="visually-hidden">Loading...</span>
                                            </div>
                                        </div>
                                        <canvas id="revenueChart" width="700" height="300"></canvas>
                                    </div>
                                </div>

                                <!--begin::Table-->
                                <table id="datatable-accrual" class="table table-hover align-middle table-row-dashed fs-6 gy-5 mb-0" hidden>
                                    <thead>
                                        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                                            <th style="width: 5%">No</th>
                                            <th>Avatar</th>
                                            <th>Nama User</th>
                                            <th>Member ID</th>
                                            <th>Cash Revenue</th>
                                            <th>Accural Revenue</th>
                                        </tr>
                                    </thead>
                                    <tbody class="text-dark fw-semibold"></tbody>
                                </table>
                                <!--end::Table-->
                            </div>
                            <div class="tab-pane fade" id="export-list" role="tabpanel" aria-labelledby="export-list-tab">
                                <!-- export-list tab content -->
                                <!--begin::Table-->
                                <table id="datatable-accrual-export" class="table table-hover align-middle table-row-dashed fs-6 gy-5 mb-0">
                                    <thead>
                                        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                                            <th style="width: 5%">No</th>
                                            <th>Tanggal Export</th>
                                            <th>Nama File</th>
                                            <th>Status</th>
                                            <th>Selesai Export</th>
                                            <th>Berkas</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody class="text-dark fw-semibold"></tbody>
                                </table>
                                <!--end::Table-->
                            </div>
                        </div>
                        <!--end::Tab content-->

                    </div>
                    <!--end::Card body-->
                </div>
                <!--end::Card-->
            </div>
            <!--end::Content container-->
        </div>
        <!--end::Content-->
    </div>
    <!--end::Content wrapper-->
</div>
@endsection

@push('js')
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/locale/id.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const monthSelect = document.getElementById('monthSelect');
        const yearSelect = document.getElementById('yearSelect');

        // Generate year options dynamically
        const currentYear = new Date().getFullYear();
        for (let year = currentYear; year >= 2013; year--) {
            const option = document.createElement('option');
            option.value = year;
            option.textContent = year;
            yearSelect.appendChild(option);
        }

        // Set initial values to current month and year
        monthSelect.value = new Date().getMonth();
        yearSelect.value = currentYear;

        // Event listener for changes
        monthSelect.addEventListener('change', updateDateRange);
        yearSelect.addEventListener('change', updateDateRange);

        function updateDateRange() {
            const selectedMonth = monthSelect.value;
            const selectedYear = yearSelect.value;
            const startDate = new Date(selectedYear, selectedMonth, 1);
            const endDate = new Date(selectedYear, +selectedMonth + 1, 0);

            // Format dates for input fields
            const formattedStartDate = moment(startDate).format('YYYY-MM-DD');
            const formattedEndDate = moment(endDate).format('YYYY-MM-DD');

            $('#loadingSpinner').show();

            axios.get("{{ route('accrual-revenue.index.chart') }}", {
                params: {
                    start_date: formattedStartDate,
                    end_date: formattedEndDate,
                }
            })
            .then(response => {
                updateChart(response.data);
            })
            .finally(() => {
                $('#loadingSpinner').hide();
            });

            // Optionally trigger data reload functions here
            // tableAccrual();
            tableExport();
        }

        // Trigger initial update
        updateDateRange();
    });
</script>
 <script>
    function validateMonthRange() {
        const startMonth = document.getElementById('startMonth').value;
        const endMonth = document.getElementById('endMonth').value;
        
        if (startMonth && endMonth && endMonth < startMonth) {
            alert('Bulan akhir tidak boleh kurang dari bulan mulai');
            document.getElementById('endMonth').value = '';
        }
    } 

    function tableAccrual() {
        var table = $('#datatable-accrual').DataTable({
            ordering: true,
            processing: true,
            serverSide: true,
            responsive: true,
            destroy: true,
            pageLength: 1,
            ajax: {
                url: "{{ route('accrual-revenue.index', ['data' => 'index']) }}",
                type: 'GET',
                data: {
                    payment: $("#payment").val(),
                    package: $("#package").val(),
                    start_date: $("#start_date").val(),
                    end_date: $("#end_date").val(),
                    status: $('#status').val()
                },
                beforeSend: function() {
                    $('#datatable tbody').empty();
                }
            },
            language: {
                "paginate": {
                    "next": "<i class='fa fa-angle-right'>",
                    "previous": "<i class='fa fa-angle-left'>"
                },
                "loadingRecords": "Loading...",
                "processing": "Processing...",
            },
            columns: [{
                    "data": null,
                    "sortable": false,
                    "searchable": false,
                    render: function(data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    }
                },
                {
                    data: 'avatar',
                    name: 'avatar',
                    orderable: false,
                    searchable: false,
                    render: function(data, type, row) {
                        if (data == null) {
                            return `
                        <div class="symbol-label h-50px w-50px rounded-circle bg-light-primary
                         d-flex justify-content-center align-items-center">
                            <span class="fs-2x fw-bold text-primary text-capitalize">
                                ${row.name.charAt(0)}</span>
                        </div>`
                        } else {
                            return `<img src="${data}" alt="image" class="h-50px w-50px rounded-circle" />`;
                        }
                    }
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'member_id',
                    name: 'member_id'
                },
                {
                    data: 'cash_revenue',
                    name: 'cash_revenue',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'accural_revenue',
                    name: 'accural_revenue',
                    orderable: false,
                    searchable: false
                }
            ]
        });

        // Menyembunyikan tabel selama proses loading
        table.on('preXhr.dt', function(e, settings, data) {
            $('#datatable tbody').empty();
        });

        // Menampilkan tabel setelah data selesai dimuat
        table.on('draw.dt', function() {
            $('#datatable').fadeIn();
        });
    }
</script>
<script>
    function tableExport() {
        var table = $('#datatable-accrual-export').DataTable({
            ordering: true,
            processing: true,
            serverSide: true,
            responsive: true,
            destroy: true,
            ajax: {
                url: "{{ route('accrual-revenue.index', ['data' => 'export']) }}"
            },
            language: {
                "paginate": {
                    "next": "<i class='fa fa-angle-right'>",
                    "previous": "<i class='fa fa-angle-left'>"
                },
                "loadingRecords": "Loading...",
                "processing": "Processing...",
            },
            columns: [{
                    "data": null,
                    "sortable": false,
                    "searchable": false,
                    render: function(data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    }
                },
                {
                    data: 'created_at',
                    name: 'created_at',
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'status',
                    name: 'status',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'completed_at',
                    name: 'completed_at',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'file',
                    name: 'file',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false
                }
            ]
        });
    }
</script>
<script>
    const ctx = document.getElementById('revenueChart').getContext('2d');
    let revenueChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [],
            datasets: [
                {
                    label: 'Cash Revenue Membership/Others',
                    data: [],
                    backgroundColor: 'rgba(0, 123, 255, 0.6)',
                    borderColor: 'rgba(0, 123, 255, 1)',
                    borderWidth: 1
                },
                {
                    label: 'Cash Revenue Coach',
                    data: [],
                    backgroundColor: 'rgba(255, 0, 0, 0.6)',
                    borderColor: 'rgba(255, 0, 0, 1)',
                    borderWidth: 1
                },
                {
                    label: 'Cash Revenue Total',
                    data: [],
                    backgroundColor: 'rgba(255, 255, 0, 0.6)',
                    borderColor: 'rgba(255, 255, 0, 1)',
                    borderWidth: 1
                },
                {
                    label: 'Accrual Revenue Membership/Others',
                    data: [],
                    backgroundColor: 'rgba(75, 0, 130, 0.6)',
                    borderColor: 'rgba(75, 0, 130, 1)',
                    borderWidth: 1
                },
                {
                    label: 'Accrual Revenue Coach',
                    data: [],
                    backgroundColor: 'rgba(255, 165, 0, 0.6)',
                    borderColor: 'rgba(255, 165, 0, 1)',
                    borderWidth: 1
                },
                {
                    label: 'Accrual Revenue Total',
                    data: [],
                    backgroundColor: 'rgba(34, 139, 34, 0.6)',
                    borderColor: 'rgba(34, 139, 34, 1)',
                    borderWidth: 1
                }
            ]
        },
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: 'CASH REVENUE & ACCROAL REVENUE'
                }
            },
            scales: {
                y: {
                    beginAtZero: true,
                    ticks: {
                        callback: function (value) {
                            return 'Rp' + value.toLocaleString();
                        }
                    }
                }
            }
        }
    });

    function updateChart(data) {
        console.log(data);
        document.getElementById('loadingSpinner').style.display = 'block';

        revenueChart.data.labels = data.labels;
        revenueChart.data.datasets.forEach((dataset, index) => {
            dataset.data = data.datasets[index];
        });
        revenueChart.update();
        document.getElementById('loadingSpinner').style.display = 'none';
    }
</script>
@endpush
