name: Deploy to VPS

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set deployment environment variables
        id: set-env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "TARGET_PATH=${{ secrets.PROD_PATH }}" >> $GITHUB_ENV
            echo "BRANCH_NAME=main" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "staging" ]; then
            echo "TARGET_PATH=${{ secrets.STAGING_PATH }}" >> $GITHUB_ENV
            echo "BRANCH_NAME=staging" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "TARGET_PATH=${{ secrets.DEV_PATH }}" >> $GITHUB_ENV
            echo "BRANCH_NAME=dev" >> $GITHUB_ENV
          fi

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            cd ${{ env.TARGET_PATH }}
            git pull origin ${{ env.BRANCH_NAME }}
            composer install --no-dev --optimize-autoloader
            npm install && npm run build && ([ -f public/build/.vite/manifest.json ] && cp public/build/.vite/manifest.json public/build/manifest.json || true)
            php artisan cache:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan livewire:publish --assets
            sudo systemctl restart php-fpm
            sudo systemctl restart nginx
